apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels: 
    app: nginx
  namespace: tony
spec: 
  containers:
  - name: nginx
    image: nginx:alpine
    imagePullPolicy: IfNotPresent 
    ports: 
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    volumeMounts: 
    - name: nginx-storage
      mountPath: /data/storage/log
  hostNetwork: true
  volumes: 
  - persistentVolumeClaim: 
      claimName: tony-local-pvc
    name: nginx-storage
