apiVersion: v1
kind: PersistentVolume
metadata: 
  name: tony-local-pv
  namespace: tony
spec: 
  accessModes: 
  - ReadWriteMany
  capacity: 
    storage: 50M
  local:
    path: /data/storage/mem_space
  storageClassName: tony-local-storage
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname 
          operator: In
          values:
          - 192.168.255.121
