apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/config.hash: a0747ae69899807a24d4eef3d2b105ee
    kubernetes.io/config.mirror: a0747ae69899807a24d4eef3d2b105ee
    kubernetes.io/config.seen: "2020-12-29T20:28:58.875417533+08:00"
    kubernetes.io/config.source: file
    prometheus.io/port: "2379"
    prometheus.io/scheme: https
    scheduler.alpha.kubernetes.io/critical-pod: ""
    tke.prometheus.io/scrape: "true"
  creationTimestamp: "2020-12-29T12:30:34Z"
  finalizers:
  - infra.tce.io/port-manager
  labels:
    component: etcd
    tier: control-plane
  name: etcd-10.200.1.133
  namespace: kube-system
  resourceVersion: "388669930"
  selfLink: /api/v1/namespaces/kube-system/pods/etcd-10.200.1.133
  uid: 0a440acb-3ecf-43fd-abc2-2637fec7ef5f
spec:
  containers:
  - command:
    - etcd
    - --advertise-client-urls=https://10.200.1.133:2379
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/data1/var/lib/etcd
    - --initial-advertise-peer-urls=https://10.200.1.133:2380
    - --initial-cluster=10.200.1.133=https://10.200.1.133:2380
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --listen-client-urls=https://127.0.0.1:2379,https://10.200.1.133:2379
    - --listen-metrics-urls=http://0.0.0.0:2381
    - --listen-peer-urls=https://10.200.1.133:2380
    - --name=10.200.1.133
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --snapshot-count=10000
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    image: registry.tce.com/library/etcd:v3.4.7
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 15
    name: etcd
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data1/var/lib/etcd
      name: etcd-data
    - mountPath: /etc/kubernetes/pki/etcd
      name: etcd-certs
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: 10.200.1.133
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    operator: Exists
  volumes:
  - hostPath:
      path: /etc/kubernetes/pki/etcd
      type: DirectoryOrCreate
    name: etcd-certs
  - hostPath:
      path: /data1/var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-12-29T12:29:05Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-12-29T12:29:07Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-12-29T12:29:07Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-12-29T12:29:05Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://c5a33c57d7160539c975426c5ba4da6383dfc782596f6f4687d8bf67c0b218cf
    image: registry.tce.com/library/etcd:v3.4.7
    imageID: docker-pullable://registry.tce.com/library/etcd@sha256:0ec52c95b6cb9699bc4e3bf47783257f4b581f84e1d25876e4935ea20414a24c
    lastState: {}
    name: etcd
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-12-29T12:29:07Z"
  hostIP: 10.200.1.133
  phase: Running
  podIP: 10.200.1.133
  podIPs:
  - ip: 10.200.1.133
  qosClass: BestEffort
  startTime: "2020-12-29T12:29:05Z"
