apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/config.hash: 50da6c02ae89a34c8b184e35f9b4fba5
    kubernetes.io/config.mirror: 50da6c02ae89a34c8b184e35f9b4fba5
    kubernetes.io/config.seen: "2020-10-02T16:19:55.529571014+08:00"
    kubernetes.io/config.source: file
    prometheus.io/port: "10252"
    prometheus.io/scheme: http
    scheduler.alpha.kubernetes.io/critical-pod: ""
    tke.prometheus.io/scrape: "true"
  creationTimestamp: "2020-12-22T14:29:19Z"
  finalizers:
  - infra.tce.io/port-manager
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager-10.200.1.133
  namespace: kube-system
  resourceVersion: "448317924"
  selfLink: /api/v1/namespaces/kube-system/pods/kube-controller-manager-10.200.1.133
  uid: f559c308-7330-4d23-9127-eebdc679c1a5
spec:
  containers:
  - command:
    - kube-controller-manager
    - --allocate-node-cidrs=true
    - --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --bind-address=127.0.0.1
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --cluster-cidr=192.168.0.0/16
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
    - --controllers=*,bootstrapsigner,tokencleaner
    - --kubeconfig=/etc/kubernetes/controller-manager.conf
    - --leader-elect=true
    - --node-cidr-mask-size=24
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --root-ca-file=/etc/kubernetes/pki/ca.crt
    - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
    - --service-cluster-ip-range=192.168.192.0/18
    - --use-service-account-credentials=true
    image: registry.tce.com/library/kube-controller-manager:v1.16.6
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 15
    name: kube-controller-manager
    resources:
      requests:
        cpu: 200m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/pki
      name: etc-pki
      readOnly: true
    - mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      name: flexvolume-dir
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
    - mountPath: /etc/kubernetes/controller-manager.conf
      name: kubeconfig
      readOnly: true
    - mountPath: /etc/kubernetes
      name: vol-dir-0
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: 10.200.1.133
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    operator: Exists
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/pki
      type: DirectoryOrCreate
    name: etc-pki
  - hostPath:
      path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      type: DirectoryOrCreate
    name: flexvolume-dir
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /etc/kubernetes/controller-manager.conf
      type: FileOrCreate
    name: kubeconfig
  - hostPath:
      path: /etc/kubernetes
      type: ""
    name: vol-dir-0
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-10-02T08:19:07Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-01-06T10:28:29Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-01-06T10:28:29Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-10-02T08:19:07Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://805b1cf0f5dcf7cc02cf32c52b36010a019ddc385dbb99c56a3cb9718b31af8c
    image: registry.tce.com/library/kube-controller-manager:v1.16.6
    imageID: docker-pullable://registry.tce.com/library/kube-controller-manager@sha256:d08f58d87fb31f1fc6f4ec1d74f3496a459b14a85288f2677b046660bc57f48c
    lastState:
      terminated:
        containerID: docker://c88d666a8b65cc3a70afaeb3127eddd07345a9b713a792a54fdf429d13fa84ce
        exitCode: 2
        finishedAt: "2021-01-06T10:25:40Z"
        reason: Error
        startedAt: "2021-01-06T10:24:10Z"
    name: kube-controller-manager
    ready: true
    restartCount: 7
    started: true
    state:
      running:
        startedAt: "2021-01-06T10:28:28Z"
  hostIP: 10.200.1.133
  phase: Running
  podIP: 10.200.1.133
  podIPs:
  - ip: 10.200.1.133
  qosClass: Burstable
  startTime: "2020-10-02T08:19:07Z"
